"""Contract-driven Task Reliability & Governance primitives for Phase 3."""

from .approval import (
    ApprovalBindingCode,
    ApprovalBindingResult,
    ApprovalDecision,
    ApprovalRequirementRef,
    ApprovalResolution,
    verify_approval_binding,
)
from .canonical import canonical_json, sha256_digest
from .completion import (
    CompletionContract,
    CompletionRequirement,
    CompletionStatus,
    CompletionValidationResult,
    EvidenceSnapshot,
    RequirementEvaluation,
    RequirementEvaluatorRegistry,
    RequirementStatus,
    SubmittedResult,
    aggregate_completion,
)
from .effects import (
    CanonicalEffectRequest,
    EffectContractError,
    EffectNormalizationCandidate,
    EffectNormalizerRegistry,
    ExternalOperation,
    ExternalOperationStatus,
    build_canonical_effect_request,
    derive_idempotency_key,
)
from .policy import (
    DecisionApplication,
    DecisionApplicationSnapshot,
    DecisionContext,
    DecisionPoint,
    PolicyAction,
    PolicyDecision,
    TaskState,
    apply_policy_decision,
    choose_policy_action,
    make_policy_decision,
    policy_action_allowed,
)
from .round2 import (
    Round2ChainResult,
    Round2Path,
    Round2ValidationReport,
    evaluate_round2_contract_chain,
    validate_round2_fixture,
)
from .governance import (
    AttemptState,
    GovernanceApplicationResult,
    GovernanceStore,
    RuntimeGovernanceCore,
    validate_governance_round2_fixture,
)
from .task_contract import (
    ApprovalRequirement,
    AuthorizedEffect,
    ContractValidationError,
    TaskContract,
    TaskContractRef,
    compute_task_contract_hash,
)

__all__ = [
    "ApprovalBindingCode",
    "ApprovalBindingResult",
    "ApprovalDecision",
    "ApprovalRequirement",
    "ApprovalRequirementRef",
    "ApprovalResolution",
    "AttemptState",
    "AuthorizedEffect",
    "CanonicalEffectRequest",
    "CompletionContract",
    "CompletionRequirement",
    "CompletionStatus",
    "CompletionValidationResult",
    "ContractValidationError",
    "DecisionApplication",
    "DecisionApplicationSnapshot",
    "DecisionContext",
    "DecisionPoint",
    "EffectContractError",
    "EffectNormalizationCandidate",
    "EffectNormalizerRegistry",
    "EvidenceSnapshot",
    "ExternalOperation",
    "ExternalOperationStatus",
    "PolicyAction",
    "PolicyDecision",
    "RequirementEvaluation",
    "RequirementEvaluatorRegistry",
    "RequirementStatus",
    "Round2ChainResult",
    "Round2Path",
    "Round2ValidationReport",
    "GovernanceApplicationResult",
    "GovernanceStore",
    "SubmittedResult",
    "TaskContract",
    "TaskContractRef",
    "RuntimeGovernanceCore",
    "TaskState",
    "aggregate_completion",
    "apply_policy_decision",
    "build_canonical_effect_request",
    "canonical_json",
    "choose_policy_action",
    "compute_task_contract_hash",
    "derive_idempotency_key",
    "evaluate_round2_contract_chain",
    "make_policy_decision",
    "policy_action_allowed",
    "sha256_digest",
    "verify_approval_binding",
    "validate_round2_fixture",
    "validate_governance_round2_fixture",
]
